Web accessibility
marcelosdata/Portfolio_Marcelov2 pull request #6
Opened 2021-12-14 21:38 UTC by marcelosdata

Using web accessibility easy checks to make create a better experience for all users

2021-12-14 22:04 UTC, marcelosdata commented
# Changes made for this project

## Following the requirements, we check for accessibility issues in the project  📖 

- Page titles: No issues found
- Image text alternatives** (<img alt="alt text">) : Changes on alternative text on projects images
- Text headings: Switch a section Tag to a Div Tag on About-section
- Color contrast: Not changed, following the template but increasing z index on the text of the grid cards
- Resize : No issues found
- Interaction : No issues were found
- Forms : Added Labels to Forms elements
- Moving content: No issues found
- Multimedia: No issues found
- The basic structure of the page: No issues were found

2021-12-14 23:02 UTC, petudeveloper requested changes
Hi @marcelosdata @kemar-art, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-14 23:02 UTC, petudeveloper commented on index.html
> +                <img src="src/Img-Placeholder-proj.svg" alt="Portfolio Image" />
To follow every requirement for this project, please [add a link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148) for every issue found. This is a good practice that helps communication and that you will surely use in your future projects.

2021-12-14 23:20 UTC, marcelosdata commented on index.html
> +                <img src="src/Img-Placeholder-proj.svg" alt="Portfolio Image" />
Hi petudeveloper, Ok I will follow your advice .First I want to ask you if **have you found** any other source on making like this? The instructions on that site are not that intuitive

2021-12-15 00:08 UTC, petudeveloper commented on index.html
> +                <img src="src/Img-Placeholder-proj.svg" alt="Portfolio Image" />
@marcelosdata I will try to explain myself better, you need to add a link to the corresponding line of code for every correction you made (for every issue). 

e.g. For every **Image text alternatives** (`<img alt="alt text ">`) you change, for every **Text headings** correction you made, for every **Form** correction you did, etc. You need to add a comment pointing to the correction. 

To do this you just need to follow this [link](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148) instructions. For a better explanation look at the images below
1. Go to the `Files changed` tab:
![Capture](https://user-images.githubusercontent.com/75709904/146098052-95b4262d-9d59-4ab1-a589-4ce120320821.PNG)
2. And then click the `+` button to add the comment in the corresponding line of code:
![Capture2](https://user-images.githubusercontent.com/75709904/146098144-fe201cc7-c22b-44b7-9909-d0f1c58293a5.PNG)

2021-12-15 16:57 UTC, marcelosdata commented on index.html
>                    <p class="feat-text">
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
>                    <p class="feat-text">
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
>                    <p class="feat-text">
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
>                    <p class="feat-text">
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
>                    <p class="feat-text">
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
>                  <div class="info">
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
> -                <img src="src/works-desktop-2.svg" alt="#" />
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
> -                <img src="src/works-desktop-3.svg" alt="#" />
Add alternative text to image

2021-12-15 17:43 UTC, marcelosdata commented on index.html
> -                <img src="src/works-desktop-4.svg" alt="#" />
Add alternative text to image

2021-12-15 17:44 UTC, marcelosdata commented on index.html
> -                <img src="src/works-desktop-2.svg" alt="#" />
Add alternative text to image

2021-12-15 17:44 UTC, marcelosdata commented on index.html
> -                <img src="src/works-desktop-3.svg" alt="#" />
Add alternative text to image

2021-12-15 17:46 UTC, marcelosdata commented on index.html
> +      <div class="about-container">
Switch a section Tag to a Div Tag on About-section

2021-12-15 17:47 UTC, marcelosdata commented on index.html
>                id="name"
Apply Label to the input in form section

2021-12-15 17:47 UTC, marcelosdata commented on index.html
>                id="email"
Apply Label to the input in form section

2021-12-15 17:47 UTC, marcelosdata commented on index.html
>                name="message"
Apply Label to the input in form section

2021-12-15 17:47 UTC, marcelosdata commented on stylev2.css
>    border-style: none;
Increase font weight and Size

2021-12-15 17:48 UTC, marcelosdata commented on stylev2.css
> +  font-weight: 700;
Diminish Opacity and increase Font Weight

2021-12-15 17:49 UTC, marcelosdata commented on stylev2.css
> +  z-index: 6;
Increase Z Index on element

2021-12-15 17:49 UTC, marcelosdata commented on stylev2.css
> +  z-index: 5;
Increase Z index to  better visuals

2021-12-15 17:58 UTC, marcelosdata commented on index.html
> +                <img src="src/Img-Placeholder-proj.svg" alt="Portfolio Image" />
Awesome, Thanks David

2021-12-15 18:15 UTC, leolpaz approved these changes
Hi @marcelosdata , 

Your project is complete!
Congratulations! 🎉🎉 

To highlight:

- Congratulations on implementing the changes requested by the previous reviewer

Now there is nothing left to do but to merge it! 🏆 

![](https://media2.giphy.com/media/l3fQc3aCV0HqpzWcU/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-15 18:20 UTC, merged